module.exports = {
  User: require('./user.model'),
  Warehouse: require('./warehouse.model'),
  Pharmacy: require('./pharmacy.model'),
  Category: require('./category.model'),
  Product: require('./product.model'),
  Offer: require('./offer.model'),
  Order: require('./order.model'),
  OrderItem: require('./orderItem.model'),
  Review: require('./review.model'),
  Return: require('./return.model'),
  Notification: require('./notification.model'),
  Otp: require('./otp.model'),
  Counter: require('./counter.model'),
  OrderRoutingLog: require('./orderRoutingLog.model'),
};
