const { Schema, model } = require('mongoose');

// A manual payment a warehouse records against a pharmacy's running debt
// (cash/transfer settled outside the app) - never generated by the system
// itself, always entered by the warehouse.
//
// Money-Flow V2 makes this APPEND-ONLY. `status` is the single field that may
// ever change (posted -> reversed, once); everything else is frozen at record
// time. A mistake is corrected by posting a `reversal` payment that references
// the original and carries a mandatory reason - never by editing or deleting
// the row, which would destroy the evidence of what was believed and when.
// Each payment posts exactly one LedgerEntry (`payment` or `payment_reversal`).
const paymentSchema = new Schema(
  {
    pharmacyId: { type: Schema.Types.ObjectId, ref: 'Pharmacy', required: true },
    warehouseId: { type: Schema.Types.ObjectId, ref: 'Warehouse', required: true },
    // What the pharmacy actually handed over, in the currency it handed it
    // over in. Kept under the original field names so existing reads and the
    // V1 rows keep working unchanged.
    amount: { type: Number, required: true, min: 0 },
    // SYP is the default currency across Phoenix - a payment recorded without
    // an explicit currency is a Syrian-pound payment. USD stays fully
    // supported (the warehouse can still pick it on the form).
    currency: { type: String, enum: ['USD', 'SYP'], required: true, default: 'SYP' },

    // Money-Flow V2 -----------------------------------------------------
    // The settled value in each currency, FROZEN at record time:
    //   SYP tender -> amountSyp = amount (exact); amountUsd = amount / fx.rate
    //   USD tender -> amountUsd = amount (exact); amountSyp = amount * fx.rate
    // amountSyp is what hits the ledger. Freezing it is what stops a later
    // exchange-rate move from re-floating an already-settled debt (the V1
    // phantom credit/debt defect).
    amountSyp: { type: Number, default: null },
    amountUsd: { type: Number, default: null },
    fx: {
      rate: { type: Number, default: null },
      source: { type: String, enum: ['api', 'manual', 'order', 'estimated', 'migration'], default: null },
      rateAsOf: { type: Date, default: null },
      estimated: { type: Boolean, default: false },
    },

    // How the money actually arrived, and any external reference for it -
    // both purely for reconciliation and the statement, neither affects a
    // figure. 'cash' is the default because that is what COD settlement is.
    method: { type: String, enum: ['cash', 'bank_transfer', 'cheque', 'other'], default: 'cash' },
    reference: { type: String, default: null, trim: true },
    // When the money actually changed hands, which can predate the moment the
    // warehouse got round to recording it. Drives the ledger entry's
    // effectiveAt, so a backdated payment lands on the statement on its real
    // date rather than its typing date. It does NOT drive the exchange rate -
    // there is no intraday rate history to look up, so a backdated payment is
    // converted at today's rate and that is stated plainly rather than faked.
    paidAt: { type: Date, default: Date.now },

    note: { type: String, default: null, trim: true },
    recordedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },

    // Money-Flow V2 lifecycle --------------------------------------------
    // Human-readable reference ("PAY-000123") for support and the statement.
    paymentNumber: { type: Number, default: null },
    // The ledger account this settles. Denormalised from (pharmacy, warehouse).
    accountId: { type: Schema.Types.ObjectId, ref: 'LedgerAccount', default: null },
    // The one LedgerEntry this payment produced ('payment' for a settlement,
    // 'payment_reversal' for a reversal).
    ledgerEntryId: { type: Schema.Types.ObjectId, ref: 'LedgerEntry', default: null },

    // A settlement is money received. A reversal undoes one - it carries the
    // same magnitude as its target (the SIGN lives on the ledger entry's
    // direction, so no money field on this model is ever negative).
    kind: { type: String, enum: ['settlement', 'reversal'], default: 'settlement' },
    // `status` is the ONLY field on this document that may ever change, and
    // only once, posted -> reversed. Everything else is frozen at record time.
    status: { type: String, enum: ['posted', 'reversed'], default: 'posted' },
    // Set on a reversal: which payment it undoes. Unique, so a payment can be
    // reversed at most once.
    reversesPaymentId: { type: Schema.Types.ObjectId, ref: 'Payment', default: null },
    // Set on the original when it is reversed - the other half of that link.
    reversedByPaymentId: { type: Schema.Types.ObjectId, ref: 'Payment', default: null },
    // Mandatory on a reversal. Recorded on both documents and in the audit log.
    reversalReason: { type: String, default: null, trim: true },

    // Client-supplied UUID. A retried request with the same key returns the
    // payment the first attempt created instead of crediting the pharmacy twice.
    idempotencyKey: { type: String, default: null },
  },
  { timestamps: true }
);

paymentSchema.index({ pharmacyId: 1, warehouseId: 1 });
// Statement / detail reads, in business-date order.
paymentSchema.index({ accountId: 1, paidAt: -1 });
// Dedupes a retried submission. Partial so the V1 rows (no key) don't collide.
paymentSchema.index(
  { idempotencyKey: 1 },
  { unique: true, partialFilterExpression: { idempotencyKey: { $type: 'string' } } }
);
// A payment is reversed at most once - the hard guard behind the status CAS.
paymentSchema.index(
  { reversesPaymentId: 1 },
  { unique: true, partialFilterExpression: { reversesPaymentId: { $type: 'objectId' } } }
);
paymentSchema.index(
  { paymentNumber: 1 },
  { unique: true, partialFilterExpression: { paymentNumber: { $type: 'number' } } }
);

module.exports = model('Payment', paymentSchema);
