const { Schema, model } = require('mongoose');

// Section 16: a manual payment a warehouse records against a pharmacy's
// running debt (cash/transfer settled outside the app) - never generated by
// the system itself, always entered by the warehouse. Feeds
// pharmacyBalance.model.js's cache; never read directly for the balance
// figure shown anywhere.
const paymentSchema = new Schema(
  {
    pharmacyId: { type: Schema.Types.ObjectId, ref: 'Pharmacy', required: true },
    warehouseId: { type: Schema.Types.ObjectId, ref: 'Warehouse', required: true },
    amount: { type: Number, required: true, min: 0 },
    currency: { type: String, enum: ['USD', 'SYP'], required: true },
    note: { type: String, default: null, trim: true },
    recordedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    // Exactly createdAt + 5 minutes, set once at creation - a short grace
    // window to fix a typo right after entry, not a general edit right.
    // Past this, the record is locked (see payment.service.js).
    canEditUntil: { type: Date, required: true },
  },
  { timestamps: true }
);

paymentSchema.index({ pharmacyId: 1, warehouseId: 1 });

module.exports = model('Payment', paymentSchema);
